version: '3'
services:
  # 后端 API 程序
  chatgpt-plus-go:
    #   image: registry.cn-hangzhou.aliyuncs.com/geekmaster/chatgpt-plus-go:v3.0.0
    image: chatplus-go:v3.0.0
    container_name: chatgpt-plus-go
    #build: ./
    restart: always
    #    network_mode: host
    ports:
      - "5678:5678"
    volumes:
      - ./conf/config.toml:/var/www/app/config.toml

  # 前端应用
  chatgpt-vue:
    #   image: registry.cn-hangzhou.aliyuncs.com/geekmaster/chatgpt-plus-vue:v3.0.0
    image: chatplus-vue:v3.0.0
    container_name: chatgpt-plus-vue
    #build: ./
    restart: always
    #    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl

