version: '3'
services:
  # 后端 API 程序
  chatgpt-plus-go:
    image: chatgpt-plus-go:v3.0.5
    container_name: chatgpt-plus-go
    restart: always
    environment:
      - DEBUG=false
      - CONFIG_FILE=config.toml
    ports:
      - "6789:5678"
    volumes:
      - ./conf/config.toml:/var/www/app/config.toml
      - ./static:/var/www/app/static

  # 前端应用
  chatgpt-vue:
    image: chatgpt-plus-vue:v3.0.5
    container_name: chatgpt-plus-vue
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl

