version: '3'
services:
  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio@pass
    command: server /data
