Listen = "0.0.0.0:5678"
ProxyURL = "http://172.22.11.200:7777"
MysqlDns = "root:mysql_pass@tcp(localhost:3306)/chatgpt_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "http://localhost:5678/static"
AesEncryptKey = "{YOUR_AES_KEY}"

[Session]
  Driver = "cookie"
  SecretKey = "m0cjm3gsuw9jk73np1ni7r42koilybjcndlycjdmq7za3pbqn7w12fyok5pqh6q5"
  Name = "CHAT_SESSION_ID"
  Path = "/"
  Domain = "localhost"
  MaxAge = 86400
  Secure = false
  HttpOnly = false
  SameSite = 2

[Manager]
  Username = "admin"
  Password = "admin123"

[Redis]
  Host = "localhost"
  Port = 6379
  Password = ""

[ApiConfig]
  ApiURL = "{URL}"
  AppId = "{APP_ID}"
  Token = "{TOKEN}"

[SmsConfig]
  AccessKey = "{YOUR_ACCESS_KEY}"
  AccessSecret = "{YOUR_SECRET_KEY}"
  Product = "Dysmsapi"
  Domain = "dysmsapi.aliyuncs.com"

[ExtConfig]
  ApiURL = "插件扩展 API 地址"
  Token = "插件扩展 API Token"