Listen = "0.0.0.0:5678"
ProxyURL = "http://172.22.11.200:7777"
MysqlDns = "root:mysql_pass@tcp(localhost:3306)/chatgpt_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "http://localhost:5678/static"
AesEncryptKey = "{YOUR_AES_KEY}"

[Session]
  SecretKey = "m0cjm3gsuw9jk73np1ni7r42koilybjcndlycjdmq7za3pbqn7w12fyok5pqh6q5"
  MaxAge = 86400

[Manager]
  Username = "admin"
  Password = "admin123"

[Redis]
  Host = "localhost"
  Port = 6379
  Password = ""

[ApiConfig]
  ApiURL = "{URL}"
  AppId = "{APP_ID}"
  Token = "{TOKEN}"

[SmsConfig]
  AccessKey = "{YOUR_ACCESS_KEY}"
  AccessSecret = "{YOUR_SECRET_KEY}"
  Product = "Dysmsapi"
  Domain = "dysmsapi.aliyuncs.com"

[ExtConfig]
  ApiURL = "插件扩展 API 地址"
  Token = "插件扩展 API Token"

 [OSS]
   Active = "local"
   [OSS.Local]
     BasePath = "./static/upload"
     BaseURL = "http://localhost:5678/static/upload"
   [OSS.Minio]
     Endpoint = "IP:端口"
     AccessKey = "minio oss access key"
     AccessSecret = "minio oss access secret"
     Bucket = "minio oss bucket"
     UseSSL = false
     Domain = "minio 文件公开访问地址"
   [OSS.QiNiu] # 七牛云 OSS 配置
       Zone = "z2" # 区域，z0：华东，z1: 华北，na0：北美，as0：新加坡
       AccessKey = "七牛云 OSS AccessKey"
       AccessSecret = "七牛云 OSS AccessSecret"
       Bucket = "七牛云 OSS Bucket"
       Domain = "OSS Bucket 所绑定的域名，如 https://img.r9it.com"
